name: "CI (dependencies): tests, linter and build"

on:
  workflow_dispatch:
  push:
    branches:
      - dependencies 
  pull_request:
    branches:
      - dependencies 

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-CI]') && github.event.head_commit.message != 'Bump version'"

    steps:
          
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Cache Cargo bin directory
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin
          key: cargo-bin-${{ runner.os }}

      - name: Check Rust formatting
        run: cargo fmt --all --check

  cargo-check:
    runs-on: ubuntu-latest
    needs: check-fmt

    steps:
          
      - name: Checkout repository
        uses: actions/checkout@v4
            
      - name: Cache Cargo target directory
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-check-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-check-

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        
      - name: Check Rust errors
        run: cargo check --all-targets --all-features

  tests:
    runs-on: ubuntu-latest
    needs: check-fmt

    steps:
          
      - name: Checkout repository
        uses: actions/checkout@v4
            
      - name: Cache Cargo target directory
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-tests-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-tests-

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        
      - name: tests
        run: cargo test

  build:
    runs-on: ubuntu-latest
    needs: [cargo-check, tests]

    steps:
          
      - name: Checkout repository
        uses: actions/checkout@v4
            
      - name: Cache Cargo target directory
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-debug-build-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-debug-build-

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: debug build
        run: cargo build